# Generated by Django 4.0 on 2023-05-22 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_condition_alter_car_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 22, 13, 22, 40, 915819)),
        ),
    ]
