# Generated by Django 4.0 on 2023-05-23 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_fuel_type_alter_car_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transmition',
        ),
        migrations.AddField(
            model_name='car',
            name='transmision',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 21, 18, 44, 851150)),
        ),
    ]
