# Generated by Django 4.0 on 2023-07-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_alter_car_created_date_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 3, 20, 1, 39, 247159)),
        ),
    ]
